creators:
  - handle: notjustabartender
    profile_url: "https://www.instagram.com/notjustabartender/"
    active: true
  - handle: kentuckyginger
    profile_url: "https://www.instagram.com/kentuckyginger/"
    active: true
  - handle: join_jules
    profile_url: "https://www.instagram.com/join_jules"
    active: true
